<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>TimetableDesigner.Backend.Events.Providers.RabbitMQ</Title>
        <Authors>Mateusz Skoczek</Authors>
        <PackageProjectUrl>https://repos.mateuszskoczek.com/TimetableDesigner</PackageProjectUrl>
        <PackageIcon>icon.png</PackageIcon>
        <RepositoryUrl>https://repos.mateuszskoczek.com/TimetableDesigner/TimetableDesigner.Backend.Events.Providers.RabbitMQ</RepositoryUrl>
        <Copyright>Mateusz Skoczek</Copyright>
        <PackageLicenseUrl>https://repos.mateuszskoczek.com/TimetableDesigner/TimetableDesigner.Backend.Events.Providers.RabbitMQ/src/branch/main/LICENSE</PackageLicenseUrl>
        <Description>Advanced school timetable editor, allows you to easily create and manage school timetable - package that support communication between microservices in the project using message queues (implementations for RabbitMQ)</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
      <PackageReference Include="timetabledesigner.backend.events" Version="1.1.7" />
    </ItemGroup>

    <ItemGroup>
      <None Update="icon.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>
</Project>
